import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar";
import {SidebarProvider} from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="relative flex items-center justify-between p-4 bg-background border-b">
            
            <div className="absolute top-2 right-4">
              <Avatar>
                <AvatarImage src="https://picsum.photos/50/50" alt="User Avatar"/>
                <AvatarFallback>FS</AvatarFallback>
              </Avatar>
            </div>
          </div>
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}



